name: TdZdd test

on:
  push:
    branches: [main]
    paths:
    - '**.cpp'
    - '**.hpp'
  pull_request:
    branches: [main]
    paths:
    - '**.cpp'
    - '**.hpp'
  workflow_dispatch:

jobs:
  test-tdzdd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make gcc g++
        version: 1.0

    - name: Test
      run: |
        cd xtal_tdzdd/test
        cmake -S . -B build
        cmake --build build
        cd build
        ctest -v
